export const BOOK_CATEGORIES = {
  FICTION: 'fiction',
  NON_FICTION: 'non-fiction',
  SCIENCE_FICTION: 'science-fiction',
  FANTASY: 'fantasy',
  MYSTERY: 'mystery',
  THRILLER: 'thriller',
  ROMANCE: 'romance',
  HISTORICAL_FICTION: 'historical-fiction',
  BIOGRAPHY: 'biography',
  AUTOBIOGRAPHY: 'autobiography',
  SELF_HELP: 'self-help',
  BUSINESS: 'business',
  TECHNOLOGY: 'technology',
  SCIENCE: 'science',
  PHILOSOPHY: 'philosophy',
  RELIGION: 'religion',
  POETRY: 'poetry',
  DRAMA: 'drama',
  CHILDREN: 'children',
  YOUNG_ADULT: 'young-adult',
  COOKING: 'cooking',
  TRAVEL: 'travel',
  HEALTH: 'health',
  EDUCATION: 'education',
  OTHER: 'other',
} as const;

export const BOOK_CATEGORIES_LIST = Object.values(BOOK_CATEGORIES);
